### PR TITLE
Add Hero component

### PR DESCRIPTION
**Pull request by sighpher**
Add Hero component

### CODE REVIEW

**Comment by sighpher** [comment]
@IanOlivierDev this probably needs a new svg for the background, but take a look at it so long.

**Comment by IanOlivierDev** [comment]
I think the background looks good. An SVG will help but other than that its really good.

**Review by IanOlivierDev — DISMISSED** [review]
Looks good!

**Comment by sighpher** [comment]
@IanOlivierDev updated the svg now, should be good for now and we can make further modifications later

**Review by IanOlivierDev — APPROVED** [review]
Great

**Pull request merged**
